name: "GreenFrame Action Local Test"
run-name: "my own greenframe GitHub-Action with local code"
on: [push]
jobs:
  # runs-on: "composite"
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: curl https://assets.greenframe.io/install.sh | bash
        shell: bash
      - run: node -v
        shell: bash
      - run: greenframe analyze https://www.google.com/
        shell: bash
      - run: greenframe analyze -C https://www.google.com/
        shell: bash
